### ISSUE TITLE
Compatibility with custom link types

### ISSUE THREAD

**Issue by amenk** [techdivision/import-product-link#25]
We are using

https://github.com/magepal/magento2-link-product

to register a custom "accessory" type in Magento.

The standard importer supports such a custom type from Magento 2.4 onwards.

What steps are necessary in this module to support such a custom link type? Or will it just work by providing accessory_sku ?

**Comment by wagnert** [comment]
@amenk I assume, that the extension uses the Magento default functionality to add a new link type, where a new row in the table `catalog_product_link_type` with code `accessory` will be added. In that case, it should be enough to add a new column `accessory_sku`.

**Comment by wagnert** [comment]
@amenk Can we close that, or do you still have problems?

**Comment by amenk** [comment]
I could not test it yet, but I believe you. Otherwise I will reopen

**Comment by wagnert** [comment]
@amenk Thank you
