### ISSUE TITLE
Importing product relations

### ISSUE THREAD

**Issue by DanieliMi** [techdivision/import-product-link#26]
How does the import of relations work?

We have a csv in the following format:
```csv
sku,related_skus,accessory_skus
```
When naming the csv "links_20200101_1.csv"  and executing `import:products` we get the following error:
> Stop processing, because can't find the mandatory OK file to process at least one of 1 files 

When naming the csv "product-import_20200101_1.csv" we get the following error:
>  Found invalid attribute set name "" in file product-import_20200101_1.csv on line 2 

The above errors appear when using the default shortcut for `ce/catalog_product/add-update`.

We tried to change the shortcut to only use the operation `ce/catalog_product/add-update.links` and the filename "links_20200101_1.csv", then the command runs through but does not import the relation. Debug mode shows notices and warnings:

> PHP Notice:  Undefined index: globalData in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 309
PHP Notice:  Undefined index: globalData in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 310
PHP Notice:  Undefined index: globalData in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 311
PHP Notice:  Undefined index: globalData in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 312
PHP Notice:  Undefined index: globalData in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 313
PHP Notice:  Undefined index: globalData in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 314
PHP Warning:  Invalid argument supplied for foreach() in vendor/techdivision/import-product/src/Subjects/AbstractProductSubject.php on line 848
PHP Notice:  Undefined index: skuEntityIdMapping in vendor/techdivision/import-product-link/src/Subjects/LinkSubject.php on line 65
 Successfully executed command import:products with serial b4a8b422-f88f-4d7d-9932-b5bc3c885989 in 00:00:00 s

**Comment by wagnert** [comment]
@DanieliMi I hat a look at the necessary configuration, and found a simple possibility for you :) I assumed that you the column `accessory_skus` you mentioned, is `associated_skus` or you've created a [new link type](https://docs.m2if.com/38/file-structure/product-import/product-links).

Please keep in mind, that with this very simple configuration, only the link types will be updated. The `updated_at` date of the product entity itself will **NOT** be refreshed. If this is o. k. for you, have fun :-)

1. Create a configuration snippet `<magento-install-dir>/app/etc/configuration/operations.json` with the content 
```json

{
  "operations": {
    "ce": {
      "catalog_product": {
        "links": {
          "plugins": {
            "subject": {
              "id": "import.plugin.subject",
              "subjects": [
                {
                  "id": "import_product.subject.bunch",
                  "file-resolver": {
                    "prefix": "product-import"
                  },
                  "params": {
                    "clean-up-empty-columns": [
                    ]
                  },
                  "observers": [
                    {
                      "import": [
                        "import_product.observer.last.entity.id",
                        "import_product_link.observer.product.link",
                        "import_product.observer.clean.up"
                      ]
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

2. Create a configuration snippet `<magento-install-dir>/app/etc/configuration/shortcuts.json` with the content
```json
{
  "shortcuts": {
    "ce": {
      "catalog_product": {
        "links": [
          "general/general/global-data",
          "general/general/move-files",
          "general/catalog_product/collect-data",
          "ce/catalog_product/links",
          "ce/catalog_product/add-update.links"
        ]
      }
    }
  }
}
```
3. Copy the CSV file, should have the structure below (at least you need columns `sku` and `related_skus`), to the directory `<magento-install-dir>/var/importexport` 
![links](https://user-images.githubusercontent.com/287509/85919732-634b1600-b86e-11ea-8caa-a8ae512f7096.png) to 
3. Execute the command `<magento-install-dir>/vendor/bin/import-simple import:products links`

**Comment by DanieliMi** [comment]
@wagnert thank you this configuration is working. `accessory_skus` is actually a custom link of ours but it's working out of the box, M2IF did import it along the default ones.

Just for me to understand can you verify that my thoughts on how it works are correct?

The observers do the following
* `import_product.observer.last.entity.id` loads the products needed to create the artifacts
* `import_product_link.observer.product.link` creates the artifacts in `links_*_1.csv`. This is the data needed by `ce/catalog_product/add-update.links`to import the links
*  `import_product.observer.clean.up`cleans up after artifact creation

And now that we have the artifacts prepared we may call the operation `ce/catalog_product/add-update.links` to actually import the links into the db.

**Comment by wagnert** [comment]
@DanieliMi You assumption is exactly how it works :-)
